title: Joseph Rochelle's Portfolio
author: Joseph Rochelle
url: ''
description: >
  Welcome to my data science portfolio. Below you will find 10 data science projects that range from classification to regression machine learning modeling. Moreover, there are many current and archived examples for future use.
permalink: '/:slug.html'
favicon: ./logo.png
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: dark
  appearance_toggle: true
  back_home_text: home..
  date_format: '%Y-%m-%d'
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_old_projects: true
  show_misc_list: false
  home:
    title_projects: Portfolio
    title_misc_list: Details
        title_old_projects: Old Projects
soopr:
  publish_token: ''
highlighter: rouge
sass:
  style: ':compressed'
plugins:
  - jekyll-feed
  - jekyll-seo-tag
baseurl: ''
